services:
  backend:
    build: .
    container_name: backup-monitor-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - /var/log:/var/log:ro
