version: "3.8"
services:
  backend:
    build: .
    container_name: backup-monitor-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      # Mount folder log dari host ke container (read-only biar aman)
      - /var/log:/var/log:ro
